import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import CustomCursor from "./componenets/ui/CustomCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 
const myFont = localFont({
  src: [
    {
      path: "../public/fonts/font.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
})

const sora = localFont({
  src: [
    { path: "../public/fonts/oslla.otf",
      weight: "900",
      style: "normal",
    },  
  ],
  variable: "--font-sora",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="cursor-none">
      <body className={`${geistSans.variable} ${geistMono.variable} ${myFont.variable} ${sora.variable}`}>
        <CustomCursor />
        {children}
      </body>
    </html>
  );
}
